title:              WANGLab
email:              zijietang0316@gmail.com
description:        WANGLab-temple university
author:             WANGLab
baseurl:            ""
url:                "https://wanglab-temple.github.io/"
root:               "/wanglab-temple.github.io"
favicon:            '{{ site.baseurl }}/assets/icons/logo.png'

# Social Profiles

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
